//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2_DevGraphique.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TP2_DevGraphique.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Autumn_Lion_icon {
            get {
                object obj = ResourceManager.GetObject("Autumn_Lion_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bas1 {
            get {
                object obj = ResourceManager.GetObject("bas1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bas2 {
            get {
                object obj = ResourceManager.GetObject("bas2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bas3 {
            get {
                object obj = ResourceManager.GetObject("bas3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream buffalo {
            get {
                return ResourceManager.GetStream("buffalo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coloriage_licorne1 {
            get {
                object obj = ResourceManager.GetObject("coloriage_licorne1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CONCIERGE_GB_1 {
            get {
                object obj = ResourceManager.GetObject("CONCIERGE_GB_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dessin_mouton {
            get {
                object obj = ResourceManager.GetObject("dessin_mouton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DessinLion {
            get {
                object obj = ResourceManager.GetObject("DessinLion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dorset_Sheep_icon {
            get {
                object obj = ResourceManager.GetObject("Dorset_Sheep_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap droite1 {
            get {
                object obj = ResourceManager.GetObject("droite1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap droite2 {
            get {
                object obj = ResourceManager.GetObject("droite2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gauche1 {
            get {
                object obj = ResourceManager.GetObject("gauche1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gauche2 {
            get {
                object obj = ResourceManager.GetObject("gauche2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap haut1 {
            get {
                object obj = ResourceManager.GetObject("haut1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap haut2 {
            get {
                object obj = ResourceManager.GetObject("haut2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap haut3 {
            get {
                object obj = ResourceManager.GetObject("haut3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream hippopotame {
            get {
                return ResourceManager.GetStream("hippopotame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream licorne {
            get {
                return ResourceManager.GetStream("licorne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream lion {
            get {
                return ResourceManager.GetStream("lion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cali
        ///Chita
        ///Darla
        ///Doli
        ///Fanny
        ///Foxy
        ///Iska
        ///Lina
        ///Luna
        ///Nicky
        ///Noisette
        ///Obie
        ///Perle
        ///Praline
        ///Prisca
        ///Quinoa
        ///Rita
        ///Ruby
        ///Samba
        ///Sissi
        ///Suzy
        ///Sweety
        ///Tess
        ///Tessy
        ///Youka
        ///Minette
        ///Chipie
        ///Câline
        ///Nala
        ///Maya
        ///Mimi
        ///Princesse
        ///Mimine
        ///Kitty
        ///Luna
        ///Isis
        ///Plume
        ///Lola
        ///Chanel
        ///Lili
        ///Lilou
        ///Noisette
        ///Vanille
        ///Zoé
        ///Clochette
        ///Nina
        ///Choupette
        ///Gribouille
        ///Mia
        ///Canelle
        ///Bella
        ///Minouche
        ///Louna
        ///Praline
        ///Fripouille
        ///Duchesse
        ///Féline
        ///Perle
        ///Iris
        ///Reglisse
        ///Cannelle
        ///Grisette
        ///Lily
        ///Gaia
        ///Neige
        ///Mina
        ///Ficelle
        ///Frimous [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string ListeNomsFeminins {
            get {
                return ResourceManager.GetString("ListeNomsFeminins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bali
        ///Charlie
        ///Enzo
        ///Félix
        ///Flacky
        ///Kenzo
        ///Léo
        ///Nougat
        ///Oliver
        ///Popeye
        ///Roméo
        ///Roucky
        ///Saxo
        ///Scott
        ///Spike
        ///Stan
        ///Tango
        ///Théo
        ///Toby
        ///Tommy
        ///Topaze
        ///Titan
        ///Voyou
        ///Yammi
        ///Yankee
        ///Tigrou
        ///Caramel
        ///Felix
        ///Simba
        ///Gribouille
        ///Filou
        ///Minou
        ///Léo
        ///Garfield
        ///Fripouille
        ///Mimi
        ///Guizmo
        ///Reglisse
        ///Titi
        ///Lucky
        ///Loulou
        ///Grisou
        ///Nougat
        ///Bounty
        ///Moustache
        ///Cookie
        ///Flocon
        ///Kiwi
        ///Oscar
        ///Oreo
        ///Titou
        ///Figaro
        ///Marley
        ///Tom
        ///Cachou
        ///Pacha
        ///Berlioz
        ///Leon
        ///Mickey
        ///Pepito
        ///Charly
        ///Salem
        ///Prince
        ///Sushi
        ///Minouche
        ///Charlie
        ///Pilou
        ///Domino        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string ListeNomsMasculins {
            get {
                return ResourceManager.GetString("ListeNomsMasculins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream mouton {
            get {
                return ResourceManager.GetStream("mouton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ours {
            get {
                return ResourceManager.GetStream("ours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Parchemin {
            get {
                object obj = ResourceManager.GetObject("Parchemin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap parking_lot_clipart_drawing_4 {
            get {
                object obj = ResourceManager.GetObject("parking_lot_clipart_drawing_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap personnages {
            get {
                object obj = ResourceManager.GetObject("personnages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UNICORN {
            get {
                object obj = ResourceManager.GetObject("UNICORN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoo_tileset {
            get {
                object obj = ResourceManager.GetObject("zoo_tileset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
